# kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker



# Steps to create a kind cluster:
# 1. Create a kind cluster 
          # kind create cluster --config kind.yaml --name sparta-cluster

# 2. Verify the cluster is running 
          # kubectl cluster-info
          # kubectl get nodes

# 3. How to delete the cluster:
          # kind delete cluster --name sparta-cluster

# 4. how to check the context:
          # kubectl config get-contexts
          # kubectl cluster-info --context kind-sparta-cluster
# 5. How to check images inside the nodes:
          # docker exec -it sparta-cluster-worker crictl images
          # docker exec -it sparta-cluster-worker crictl rmi docker.io/sidraut007/todo-backend:4
          # docker exec -it sparta-cluster-worker crictl rmi docker.io/sidraut007/todo-frontend:4
