apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  labels:
    app: bankapp
spec:
  selector:
    app: bankapp
  ports:
    - protocol: TCP
      port: 80             #Port on the service
      targetPort: 8080     #Port on the container
  type: ClusterIP