apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==      #Base64 encoded value of "root"
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjM0  #Base64 encoded value of "Test@1234"
  