apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-configmap
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/bankapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  