apiVersion: v1
kind: Service
metadata:
  name: mysql-service   
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql          
  ports:
    - protocol: TCP
      port: 3306         #Port on the service
      targetPort: 3306   #Port on the container